### ISSUE TITLE
Guru meditation error

### ISSUE THREAD

**Issue by priyansh-shankhdhar** [ThingPulse/esp32-icon64-a2dp#1]
when i am decreasing the no. of LED's say less than 64 then i am receiving a Guru meditation error . can you help me regarding this. The system keeps rebooting.

**Comment by marcelstoer** [comment]
While there is a `NUM_LEDS` constant at https://github.com/ThingPulse/esp32-icon64-a2dp/blob/master/src/main.cpp#L47 there appear to be a number of places that ignore it and just expect the number of LEDs to be 8x8. You'd have to adjust those as well I guess.
- https://github.com/ThingPulse/esp32-icon64-a2dp/blob/master/src/main.cpp#L94
- https://github.com/ThingPulse/esp32-icon64-a2dp/blob/master/src/main.cpp#L160
- https://github.com/ThingPulse/esp32-icon64-a2dp/blob/master/src/main.cpp#L181
- maybe more?
